name: Build

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Linux build
        run: cargo build --verbose --release --target x86_64-unknown-linux-gnu

      - name: Windows build
        run: |
          rustup target add x86_64-pc-windows-gnu
          cargo build --verbose --release --target x86_64-pc-windows-gnu
      
      - name: Extract version
        if: startsWith(github.ref, 'refs/tags/v')
        id: version
        run: echo "version=$(git describe --tags --always)" >> "$GITHUB_OUTPUT"

      - name: Create a release tarball
        if: startsWith(github.ref, 'refs/tags/v')
        run: tar --exclude='./target' --exclude='./.*' -czf ./target/cetrainer-unpacker-${{ steps.version.outputs.version }}.tar.gz .
      
      - name: Publish release (version tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: true
          files: |
            target/cetrainer-unpacker.tar.gz
            target/x86_64-unknown-linux-gnu/release/cetrainer-unpacker
            target/x86_64-pc-windows-gnu/release/cetrainer-unpacker.exe

      - name: Publish pre-release (push to master)
        if: github.ref == 'refs/heads/master'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          title: Development build
          prerelease: true
          files: |
            target/x86_64-unknown-linux-gnu/release/cetrainer-unpacker
            target/x86_64-pc-windows-gnu/release/cetrainer-unpacker.exe